// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QTimeRecord.Core.Data;

#nullable disable

namespace QTimeRecord.Core.Data.Migrations
{
    [DbContext(typeof(QTimeRecordDbContext))]
    partial class QTimeRecordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("QTimeRecord.Core.Domain.AdminCredential", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT")
                        .HasColumnName("store_id");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_count");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iterations");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("salt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("StoreId")
                        .HasName("pk_admin_credentials");

                    b.ToTable("admin_credentials");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_order");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("heading");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.HasIndex("StoreId", "DisplayOrder")
                        .HasDatabaseName("ix_announcements_store_id_display_order");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.DeviceSettings", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT")
                        .HasColumnName("store_id");

                    b.Property<int>("BaudRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("baud_rate");

                    b.Property<string>("ComPort")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("com_port");

                    b.Property<int>("DataBits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_bits");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("parity");

                    b.Property<string>("StopBits")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_bits");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("StoreId")
                        .HasName("pk_device_settings");

                    b.ToTable("device_settings");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("employment_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameKana")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_kana");

                    b.Property<string>("StaffNo")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.HasIndex("StoreId", "StaffNo")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_store_id_staff_no")
                        .HasFilter("staff_no IS NOT NULL");

                    b.HasIndex("StoreId", "Status")
                        .HasDatabaseName("ix_staff_store_id_status");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.StaffQrToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_id");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT")
                        .HasColumnName("store_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff_qr_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_qr_tokens_token");

                    b.HasIndex("StaffId", "RevokedAt")
                        .HasDatabaseName("ix_staff_qr_tokens_staff_id_revoked_at");

                    b.ToTable("staff_qr_tokens");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AnnouncementTitle")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("announcement_title");

                    b.Property<TimeOnly>("BusinessDayEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_day_end");

                    b.Property<TimeOnly>("BusinessDayStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_day_start");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("StoreCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("store_code");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("store_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stores");

                    b.ToTable("stores");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.TimeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EntryMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_method");

                    b.Property<bool>("IsOutsideBusinessHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_outside_business_hours");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("record_type");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_id");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("work_date");

                    b.HasKey("Id")
                        .HasName("pk_time_records");

                    b.HasIndex("StaffId", "RecordedAt")
                        .HasDatabaseName("ix_time_records_staff_id_recorded_at");

                    b.HasIndex("StaffId", "WorkDate")
                        .HasDatabaseName("ix_time_records_staff_id_work_date");

                    b.HasIndex("StoreId", "WorkDate")
                        .HasDatabaseName("ix_time_records_store_id_work_date");

                    b.ToTable("time_records");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.AdminCredential", b =>
                {
                    b.HasOne("QTimeRecord.Core.Domain.Store", "Store")
                        .WithOne()
                        .HasForeignKey("QTimeRecord.Core.Domain.AdminCredential", "StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_credentials_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.Announcement", b =>
                {
                    b.HasOne("QTimeRecord.Core.Domain.Store", "Store")
                        .WithMany("Announcements")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_announcements_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.DeviceSettings", b =>
                {
                    b.HasOne("QTimeRecord.Core.Domain.Store", "Store")
                        .WithOne()
                        .HasForeignKey("QTimeRecord.Core.Domain.DeviceSettings", "StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_settings_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.Staff", b =>
                {
                    b.HasOne("QTimeRecord.Core.Domain.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.StaffQrToken", b =>
                {
                    b.HasOne("QTimeRecord.Core.Domain.Staff", "Staff")
                        .WithMany("QrTokens")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_qr_tokens_staff_staff_id");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.TimeRecord", b =>
                {
                    b.HasOne("QTimeRecord.Core.Domain.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_time_records_staff_staff_id");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.Staff", b =>
                {
                    b.Navigation("QrTokens");
                });

            modelBuilder.Entity("QTimeRecord.Core.Domain.Store", b =>
                {
                    b.Navigation("Announcements");
                });
#pragma warning restore 612, 618
        }
    }
}
